---
- hosts: all
  become: no
  tasks:

  - name: Install mosh
    become: yes
    apt:
      name: mosh
      state: present

  - name: Download cord-in-a-box.sh script
    shell: curl https://gerrit.opencord.org/changes/1310/revisions/8d02ed0d144dc8066f024dfb27edb464cc911e62/archive?format=tar | tar -xf - scripts/cord-in-a-box.sh
    register: result
    until: result | success
    retries: 3
    delay: 1

  - name: Run cord-in-a-box.sh script
    shell: ~/scripts/cord-in-a-box.sh -t | tee ~/cord-in-a-box.out
    async: 14400
    poll: 60

  - name: Fetch log
    fetch: src=~/cord-in-a-box.out dest=logs